#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

# Complete the countTriplets function below.
def countTriplets(arr, r):
    count = Counter()
    count2 = Counter()
    for i in arr: 
        count[i]+=1
    for j in count:
        if(r != 1):
            count2[j]=count[j]*count[j*r]*count[j*r*r]
        else:
            a = count[j]
            count2[j]=int(a*(a-1)*(a-2)/6)
    return sum(count2.values())
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nr = input().rstrip().split()

    n = int(nr[0])

    r = int(nr[1])

    arr = list(map(int, input().rstrip().split()))

    ans = countTriplets(arr, r)

    fptr.write(str(ans) + '\n')

    fptr.close()
